# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2424db8ef11c49761dbd2b8fda779d226bbbd4ba117ed8627a49edb01316ead5a1493cd3130ab31c6b8d745731c9d7ea6d1906a91a01f93d6ff0276d599f583f

test:
  secret_key_base: 17055796513584878167a7b822c961157c26fcf7f5990fa5ba08e2818a8619f951e4caad3cde33db66024b3eb5d1ae90b328fe7196b528a322dad4e8c443608d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
